In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn import metrics
from sklearn.metrics import accuracy_score

In [2]:
cv = CountVectorizer()

In [3]:
x_traincv = cv.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome"])

In [4]:
a=x_traincv.toarray()

In [5]:
cv.get_feature_names()

['are', 'awesome', 'doing', 'hi', 'how', 'that', 'up', 'what', 'wow', 'you']

In [6]:
a[0]

array([2, 0, 1, 1, 2, 0, 0, 0, 0, 2])

In [7]:
cv.inverse_transform(a[0])

[array(['are', 'doing', 'hi', 'how', 'you'], dtype='<U7')]

In [8]:
a[1]

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0])

In [9]:
cv.inverse_transform(a[1])

[array(['hi', 'up', 'what'], dtype='<U7')]

In [10]:
a[2]

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [11]:
cv.inverse_transform(a[2])

[array(['awesome', 'that', 'wow'], dtype='<U7')]

In [12]:
a

array([[2, 0, 1, 1, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0]])