In [99]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn import metrics
from sklearn.metrics import accuracy_score

In [100]:
df=pd.read_csv('SMSSpamCollection',sep='\t',names=['Status','Message'])

In [101]:
type(df)

pandas.core.frame.DataFrame

In [102]:
df.shape

(5572, 2)

In [103]:
df.head()

Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [104]:
len(df)

5572

In [105]:
df['Status'].value_counts()

ham     4825
spam     747
Name: Status, dtype: int64

In [106]:
len(df[df.Status=='spam'])

747

In [107]:
len(df[df.Status=='ham'])

4825

In [108]:
df.loc[df["Status"]=='ham',"Status",]=1

In [109]:
df.loc[df["Status"]=='spam',"Status",]=0

In [110]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [111]:
df_x=df["Message"]
df_y=df["Status"]

In [112]:
type(df_y)

pandas.core.series.Series

In [113]:
cv = CountVectorizer()

In [114]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [115]:
x_train.head()

1457    U sleeping now.. Or you going to take? Haha.. ...
472     How long has it been since you screamed, princ...
2481    Urgent! call 09066612661 from landline. Your c...
243     Okay. No no, just shining on. That was meant t...
1413    Wen ur lovable bcums angry wid u, dnt take it ...
Name: Message, dtype: object

In [116]:
x_train.shape

(4457,)

In [117]:
cv1 = CountVectorizer()

In [118]:
x_traincv=cv1.fit_transform(x_train)

In [119]:
type(x_traincv)

scipy.sparse.csr.csr_matrix

In [120]:
a=x_traincv.toarray()

In [121]:
a.shape

(4457, 7762)

In [122]:
a[0]

array([0, 0, 0, ..., 0, 0, 0])

In [123]:
len(cv1.get_feature_names())

7762

In [124]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'me', 'now',
        'online', 'or', 'replying', 'sleeping', 'spys', 'take', 'to',
        'wat', 'you'], dtype='<U27')]

In [125]:
cv1.inverse_transform(a[3])

[array(['be', 'better', 'but', 'just', 'meant', 'no', 'okay', 'on',
        'shining', 'signing', 'sounds', 'that', 'to', 'was'], dtype='<U27')]

In [126]:
x_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [127]:
x_testcv=cv1.transform(x_test)

In [128]:
x_testcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [129]:
x_testcv.shape

(1115, 7762)

In [130]:
 mnb = MultinomialNB()

In [131]:
y_train=y_train.astype('int')

In [132]:
type(y_train)

pandas.core.series.Series

In [133]:
y_train

1457    1
472     1
2481    0
243     1
1413    1
       ..
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int64

In [134]:
mnb.fit(x_traincv,y_train)

MultinomialNB()

In [135]:
#testmessage=x_test.iloc[0]

In [136]:
predictions=mnb.predict(x_testcv)

In [137]:
predictions

array([1, 1, 1, ..., 1, 1, 0])

In [138]:
a=np.array(y_test)

In [139]:
a

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [140]:
count=0

In [141]:
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [142]:
count

1092

In [143]:
len(predictions)

1115

In [144]:
1092/1115.0

0.979372197309417

In [145]:
y_test = np.array(y_test)

In [146]:
y_test=y_test.astype('int')

In [147]:
print(accuracy_score(y_test, predictions))

0.979372197309417
